<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\Business;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DirectoryTestSeeder extends Seeder
{
    /**
     * ✅ Owners with active subscriptions — their business profile pages work.
     *    Owners 3, 5, 8 from your DB.
     */
    private const OWNER_IDS = [3, 5, 8];

    /**
     * ✅ Target cities with their region IDs.
     */
    private const CITIES = [
        ['id' => 1,  'region_id' => 9, 'name' => 'Buea'],
        ['id' => 2,  'region_id' => 9, 'name' => 'Limbe'],
        ['id' => 9,  'region_id' => 5, 'name' => 'Douala'],
        ['id' => 10, 'region_id' => 2, 'name' => 'Yaounde'],
    ];

    private const COUNTRY_ID = 1;

    public function run(): void
    {
        $categories = Category::where('is_active', true)->get();

        if ($categories->isEmpty()) {
            $this->command->error('No active categories found. Aborting.');
            return;
        }

        $this->command->info("Seeding 2 businesses per category across " . count($categories) . " categories...");

        $created = 0;
        $skipped = 0;

        foreach ($categories as $category) {
            for ($i = 1; $i <= 2; $i++) {
                $name = "Seed {$category->name} #{$i}";

                // ✅ Idempotency — skip if this business already exists
                if (Business::withTrashed()->where('name', $name)->exists()) {
                    $skipped++;
                    continue;
                }

                $ownerId = self::OWNER_IDS[array_rand(self::OWNER_IDS)];
                $city = self::CITIES[array_rand(self::CITIES)];

                $business = Business::create([
                    'owner_id' => $ownerId,
                    'name' => $name,
                    'slug' => null, // auto-generated by boot hook
                    'description' => $this->description($category->name, $city['name']),
                    'email' => 'seed-' . Str::random(8) . '@example.test',
                    'website' => null,
                    // ✅ phone lives on branches, not businesses
                    'status' => Business::STATUS_PUBLISHED,
                    'published_at' => now()->subDays(random_int(1, 60)),
                    'is_featured' => $i === 1 && random_int(0, 3) === 0,
                ]);

                // ✅ Attach category as primary
                $business->categories()->attach($category->id, ['is_primary' => true]);

                // ✅ Create a primary branch in the target city
                Branch::create([
                    'business_id' => $business->id,
                    'name' => $city['name'] . ' Branch',
                    'is_primary' => true,
                    'country_id' => self::COUNTRY_ID,
                    'region_id' => $city['region_id'],
                    'city_id' => $city['id'],
                    'address' => 'Seed address ' . Str::random(6),
                    'latitude' => null,
                    'longitude' => null,
                    'phone' => '+237' . random_int(600000000, 699999999),
                    'whatsapp' => null,
                    'status' => Branch::STATUS_ACTIVE,
                    'sort_order' => 0,
                ]);

                $created++;
            }
        }

        $this->command->info("✅ Created {$created} businesses.");
        $this->command->info("⏭️  Skipped {$skipped} (already exist).");
        $this->command->newLine();
        $this->command->warn('⚠️  Required follow-up:');
        $this->command->line('   php artisan scout:import "App\Models\Business"');
        $this->command->line('   php artisan cache:clear');
        $this->command->newLine();
        $this->command->info('🧹 To remove seeded businesses later:');
        $this->command->line('   php artisan tinker');
        $this->command->line('   >>> App\Models\Business::where(\'name\', \'like\', \'Seed %\')->get()->each->delete();');
    }

    private function description(string $categoryName, string $cityName): string
    {
        return "A trusted {$categoryName} in {$cityName}. We provide quality service and have served the community for years. Contact us for more information about our offerings and hours.";
    }
}