<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing plans
        Plan::query()->delete();

        $plans = [
            [
                'name' => 'Free',
                'slug' => 'free',
                'tier' => 'free',
                'description' => 'Perfect for getting your business online',
                'tagline' => 'Get discovered for free',
                'price_monthly' => 0,
                'price_yearly' => 0,
                'yearly_discount_percentage' => 0,
                'max_businesses' => 1,
                'max_branches' => 1,
                'max_services' => 3,
                'max_images' => 3,
                'max_coupons' => 0,
                'max_staff' => 0,
                'is_active' => true,
                'is_featured' => false,
                'is_popular' => false,
                'sort_order' => 1,
                'trial_days' => 0,
                'features' => [
                    'whatsapp_button' => false,
                    'phone_display' => false,
                    'respond_to_reviews' => false,
                    'featured_listing' => false,
                    'verified_badge' => false,
                    'analytics' => 'basic',
                    'coupons' => false,
                    'priority_support' => false,
                    'homepage_feature' => false,
                    'custom_branding' => false,
                    'booking_system' => false,
                    'lead_capture' => false,
                    'branch_hours' => false,
                ],
                'feature_list' => [
                    '1 business listing',
                    'Up to 3 photos',
                    'Up to 3 services',
                    'Basic business profile',
                    'Customer reviews (receive only)',
                    'Basic analytics',
                    'Email contact only',
                ],
            ],
            [
                'name' => 'Starter',
                'slug' => 'starter',
                'tier' => 'starter',
                'description' => 'For growing businesses ready to stand out',
                'tagline' => 'Start getting more customers',
                'price_monthly' => 1000,
                'price_yearly' => 10000,
                'yearly_discount_percentage' => 16.67,
                'max_businesses' => 1,
                'max_branches' => 2,
                'max_services' => 10,
                'max_images' => 15,
                'max_coupons' => 1,
                'max_staff' => 1,
                'is_active' => true,
                'is_featured' => false,
                'is_popular' => true,
                'sort_order' => 2,
                'trial_days' => 14,
                'badge_text' => 'MOST POPULAR',
                'badge_color' => 'primary',
                'features' => [
                    'whatsapp_button' => true,
                    'phone_display' => true,
                    'respond_to_reviews' => true,
                    'featured_listing' => false,
                    'verified_badge' => false,
                    'analytics' => 'standard',
                    'coupons' => true,
                    'priority_support' => false,
                    'homepage_feature' => false,
                    'custom_branding' => false,
                    'booking_system' => false,
                    'lead_capture' => false,
                    'branch_hours' => true,
                ],
                'feature_list' => [
                    '1 business listing',
                    'Up to 15 photos',
                    'Up to 10 services',
                    'Up to 2 branches',
                    'WhatsApp & phone contact',
                    'Respond to reviews',
                    '1 active coupon',
                    'Standard analytics',
                    'Email support',
                ],
            ],
            [
                'name' => 'Growth',
                'slug' => 'growth',
                'tier' => 'growth',
                'description' => 'For established businesses scaling up',
                'tagline' => 'Get featured and grow faster',
                'price_monthly' => 2000,
                'price_yearly' => 20000,
                'yearly_discount_percentage' => 16.67,
                'max_businesses' => 3,
                'max_branches' => 5,
                'max_services' => 25,
                'max_images' => 50,
                'max_coupons' => 5,
                'max_staff' => 3,
                'is_active' => true,
                'is_featured' => true,
                'is_popular' => false,
                'sort_order' => 3,
                'trial_days' => 14,
                'badge_text' => 'BEST VALUE',
                'badge_color' => 'purple',
                'features' => [
                    'whatsapp_button' => true,
                    'phone_display' => true,
                    'respond_to_reviews' => true,
                    'featured_listing' => true,
                    'verified_badge' => true,
                    'analytics' => 'advanced',
                    'coupons' => true,
                    'priority_support' => true,
                    'homepage_feature' => true,
                    'custom_branding' => true,
                    'booking_system' => false,
                    'lead_capture' => true,
                    'branch_hours' => true,
                ],
                'feature_list' => [
                    'Up to 3 business listings',
                    'Up to 50 photos',
                    'Up to 25 services',
                    'Up to 5 branches',
                    'WhatsApp & phone contact',
                    'Respond to reviews',
                    'Verified badge',
                    'Featured listing (rotating)',
                    '5 active coupons',
                    'Advanced analytics',
                    'Lead capture forms',
                    'Homepage feature',
                    'Priority email + chat support',
                ],
            ],
            [
                'name' => 'Premium',
                'slug' => 'premium',
                'tier' => 'premium',
                'description' => 'Maximum visibility for market leaders',
                'tagline' => 'Dominate your category',
                'price_monthly' => 3000,
                'price_yearly' => 30000,
                'yearly_discount_percentage' => 16.67,
                'max_businesses' => -1,
                'max_branches' => -1,
                'max_services' => -1,
                'max_images' => -1,
                'max_coupons' => -1,
                'max_staff' => -1,
                'is_active' => true,
                'is_featured' => false,
                'is_popular' => false,
                'sort_order' => 4,
                'trial_days' => 14,
                'badge_text' => 'ENTERPRISE',
                'badge_color' => 'gold',
                'features' => [
                    'whatsapp_button' => true,
                    'phone_display' => true,
                    'respond_to_reviews' => true,
                    'featured_listing' => true,
                    'verified_badge' => true,
                    'analytics' => 'enterprise',
                    'coupons' => true,
                    'priority_support' => true,
                    'homepage_feature' => true,
                    'custom_branding' => true,
                    'booking_system' => true,
                    'lead_capture' => true,
                    'branch_hours' => true,
                ],
                'feature_list' => [
                    'Unlimited business listings',
                    'Unlimited photos',
                    'Unlimited services',
                    'Unlimited branches',
                    'Everything in Growth',
                    'Verified gold badge',
                    'Premium featured spot',
                    'Unlimited coupons',
                    'Enterprise analytics',
                    'Booking system',
                    'Custom branding',
                    'VIP priority support',
                ],
            ],
        ];

        foreach ($plans as $plan) {
            Plan::create($plan);
        }
    }
}